name: TokenSMP
main: com.example.tokensmp.TokenSMP
version: 1.0
api-version: 1.20
commands:
  givetoken:
    description: Give a token
    usage: /givetoken <player> <token>
    permission: tokensmp.admin
  tokensmp:
    description: TokenSMP command
    usage: /tokensmp <list|reload>
    permission: tokensmp.admin
permissions:
  tokensmp.admin:
    default: op
    
